print("Welcome to BUK students portal")
a=float(input("Enter Maths 101 marks:"))
b=float(input("Enter Chem 101 marks:"))
c=float(input("Enter Phy 101 marks:"))
d=float(input("Enter Maths 102 marks:"))
e=float(input("Enter Maths 103 marks:"))
Total=(a+b+c+d+e)
print("Total is:", str(Total))
Percentage=(Total)*(100/500)
print("Percentage is:", str(Percentage))
