print("Basic operations of numbers +-*/")
a=float(input("\nEnter the value of a:"))
b=float(input("\nEnter the value of b:"))
mul=(a*b)
div=(a/b)
add=(a+b)
sub=(a-b)
mod=(a%b)
print("Multiplication",mul, "Division",div, "Addition",add, "Subtraction",sub, "Modulo",mod )
