print("calculate the percentage of a student")
a=float(input("Enter the marks for a:"))
b=float(input("Enter the marks for b:"))
c=float(input("Enter the marks for c:"))
d=float(input("Enter the marks for d:"))
e=float(input("Enter the marks for e:"))
Total=(a+b+c+d+e)
Percentage=(Total)*(100/500)
print("Calculate the Total:", str(Total))
print("Calculate the Percentage:", str(Percentage))